FROM debian:bookworm-slim

ARG HUGO_VERSION=0.147.1
ARG GH_VERSION=2.72.0

RUN apt-get update && apt-get install -y \
    curl git python3 python3-pip make \
    && rm -rf /var/lib/apt/lists/*

# Hugo extended
RUN curl -sL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz \
    | tar xz -C /usr/local/bin hugo

# gh CLI
RUN curl -sL https://github.com/cli/cli/releases/download/v${GH_VERSION}/gh_${GH_VERSION}_linux_amd64.tar.gz \
    | tar xz -C /tmp \
    && mv /tmp/gh_${GH_VERSION}_linux_amd64/bin/gh /usr/local/bin/gh

WORKDIR /site
