baseURL = "https://www.stefannegele.de/"
languageCode = "de"
title = "Stefan Negele"

[params]
  author = "Stefan Negele"
  description = "Articles on data architecture, distributed systems, and software engineering."

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "dracula"

disableKinds = ["taxonomy", "term"]
